name: Job - Lint check

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5
      - name: Run linter
        run: cargo clippy
      - name: Run Formatter
        run: cargo fmt -- --check
